### ISSUE TITLE
Autoreflection of secret failing in a loop: "Source no longer permits reflection"

### ISSUE THREAD

**Issue by morlando016** [emberstack/kubernetes-reflector#313] opened 2022-11-03 18:31 UTC
I am trying to copy a certificate from one namespace to another. It looks like it is initially able to copy over the secret to the other namespace but then it immediately deletes the copied secret and says it no longer permits reflection. It then does this in a loop over and over.
```
2022-11-03 18:22:07.672 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected nucleus-sandbox/internal-nucleus-sandbox-hxp-hyland-com-wildcard-tls where permitted. Created 1 - Updated 0 - Deleted 0 - Validated 0.
2022-11-03 18:22:07.695 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created apps-sandbox/internal-nucleus-sandbox-hxp-hyland-com-wildcard-tls as a reflection of nucleus-sandbox/internal-nucleus-sandbox-hxp-hyland-com-wildcard-tls
2022-11-03 18:22:07.695 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting apps-sandbox/internal-nucleus-sandbox-hxp-hyland-com-wildcard-tls - Source nucleus-sandbox/internal-nucleus-sandbox-hxp-hyland-com-wildcard-tls no longer permits reflection.
2022-11-03 18:59:07.233 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.Kubernetes.DeleteNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.DeleteNamespacedSecretAsync(IKubernetes operations, String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.TriggerAutoReflectionForSource(KubeRef resourceRef, KubeRef reflectionRef, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 306
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, WatchEventType eventType, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 263
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 75
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 47
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
```

Looking at the deployed cert, it looks like it is configured to allow auto reflection of the secret. Why is not not copying the secret over?
```
Secret Template:
    Annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed:             true
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces:  apps-sandbox
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled:        true
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces:     apps-sandbox
```

**Comment by Xilosof** [comment] 2023-02-05 13:50
I have the same problem.
```
2023-02-05 13:39:47.994 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2023-02-05 13:39:48.086 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Processing auto-reflection source kube-system/tls-staging-secret
2023-02-05 13:39:48.177 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected kube-system/tls-staging-secret where permitted. Created 3 - Updated 0 - Deleted 0 - Validated 0.
2023-02-05 13:39:48.177 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting kube-system/tls-staging-secret to default/tls-staging-secret
2023-02-05 13:39:48.203 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created default/tls-staging-secret as a reflection of kube-system/tls-staging-secret
2023-02-05 13:39:48.203 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting kube-system/tls-staging-secret to kube-public/tls-staging-secret
2023-02-05 13:39:48.238 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created kube-public/tls-staging-secret as a reflection of kube-system/tls-staging-secret
2023-02-05 13:39:48.238 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting kube-system/tls-staging-secret to kube-node-lease/tls-staging-secret
2023-02-05 13:39:48.266 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created kube-node-lease/tls-staging-secret as a reflection of kube-system/tls-staging-secret
2023-02-05 13:39:48.266 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting default/tls-staging-secret - Source kube-system/tls-staging-secret no longer permits reflection.
2023-02-05 13:39:48.322 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting kube-public/tls-staging-secret - Source kube-system/tls-staging-secret no longer permits reflection.
2023-02-05 13:39:48.361 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting kube-node-lease/tls-staging-secret - Source kube-system/tls-staging-secret no longer permits reflection.
2023-02-05 13:39:48.439 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Processing auto-reflection source kube-system/tls-staging-secret
2023-02-05 13:39:48.524 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected kube-system/tls-staging-secret where permitted. Created 3 - Updated 0 - Deleted 0 - Validated 0.
2023-02-05 13:39:48.524 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting kube-system/tls-staging-secret to default/tls-staging-secret
2023-02-05 13:39:48.561 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created default/tls-staging-secret as a reflection of kube-system/tls-staging-secret
2023-02-05 13:39:48.561 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting kube-system/tls-staging-secret to kube-public/tls-staging-secret
2023-02-05 13:39:48.586 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created kube-public/tls-staging-secret as a reflection of kube-system/tls-staging-secret
2023-02-05 13:39:48.586 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting kube-system/tls-staging-secret to kube-node-lease/tls-staging-secret
2023-02-05 13:39:48.616 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created kube-node-lease/tls-staging-secret as a reflection of kube-system/tls-staging-secret
2023-02-05 13:39:48.617 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting default/tls-staging-secret - Source kube-system/tls-staging-secret no longer permits reflection.
2023-02-05 13:39:48.667 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting kube-public/tls-staging-secret - Source kube-system/tls-staging-secret no longer permits reflection.
2023-02-05 13:39:48.705 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Deleting kube-node-lease/tls-staging-secret - Source kube-system/tls-staging-secret no longer permits reflection.
2023-02-05 13:39:48.767 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.Kubernetes.DeleteNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.DeleteNamespacedSecretAsync(IKubernetes operations, String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.TriggerAutoReflectionForSource(KubeRef resourceRef, KubeRef reflectionRef, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 306
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, WatchEventType eventType, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 263
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 75
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 47
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2023-02-05 13:39:48.782 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:00.7878893. Faulted: True.
```

I am not sure that I have configured everything correctly. Perhaps it is worth adding a guide on how to properly use reflector together with cert-manager. The certmanager documentation also describes the setup process very sparsely.

**Comment by Xilosof** [comment] 2023-02-05 14:17
Also events log looks like
```
root@1141233-cq99499:~# kubectl get events -A
NAMESPACE      LAST SEEN   TYPE     REASON              OBJECT                              MESSAGE
argo           60m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    60m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           60m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    60m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           60m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    60m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           60m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    60m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           59m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    59m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           59m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    59m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           59m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    59m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           58m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
kube-system    58m         Normal   CreateCertificate   ingress/echo                        Successfully created Certificate "tls-staging-secret"
argo           58m         Normal   CreateCertificate   ingress/argo-server                 Successfully created Certificate "tls-staging-secret"
```

**Comment by winromulus** [comment] 2023-03-05 01:02
Please try the new version. This issue should be fixed. Please reopen if this is still a problem (some scenarios are extremely hard to reproduce and help is required to validate the fix).

**Closed by winromulus** 2023-03-05 01:02 UTC
Labels: bug

**Comment by SophiaHadash** [comment] 2023-10-18 16:49
I'm having the exact same issue on tag build-7.1.217
