### ISSUE TITLE
[BUG] reflector does not update secrets anymore after some time - restart fixes the problem (continues)

### ISSUE THREAD

**Issue by marktlc** [emberstack/kubernetes-reflector#337] opened 2023-03-07 21:01 UTC
Hi @winromulus 

Thanks for the update on this issue.  I've updated our version of Reflector to the latest.  I waited approximately 2 hours before testing and the issue still appears to occur.  I followed the steps below to reproduce the issue.

1) Updated Reflector
2) Approx 2hrs later - updated a secret.
3) Secret did not replicate - nothing shown in the logs.
4) Restarted Reflector, Secret then replicates successfully immediately.

The logs don't really offer anything of value, so haven't included, but let us know if we can provide any more diagnostic info.

Thanks,
Mark

_Originally posted by @marktlc in https://github.com/emberstack/kubernetes-reflector/issues/292#issuecomment-1455248818_

**Comment by winromulus** [comment] 2023-03-07 21:40
@marktlc  please include the full logs. They should include session timeout information. Also please provide the version of k8s you have and if this is cloud or self hosted.

**Comment by marktlc** [comment] 2023-03-08 04:55
I'm just trying to replicate the issue again - it can take anywhere from 2 hours to a few days to occur it seems.  I'll report back either way when / if we see the issue again.   

We're running Google Anthos and have clusters in GCP, AWS and OnPrem - Kubernetes version 1.24.9

**Comment by laemm-line** [comment] 2023-03-12 16:17
I can reproduce this issue with version 7.0.151 on my k3s 1.26.2 cluster.

It worked directly after deployment, secrets got reflected to a newly created namespace.
Then I tried it again ~2 hours later by creating another new namespace, and now it does not work anymore: Secrets are not copied and there is nothing happening in the logs.

Here are the logs, I redacted only some names of secrets and namespaces:
```
2023-03-12 13:38:38.635 +00:00 [INF] () Starting host
2023-03-12 13:38:39.718 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2023-03-12 13:38:39.832 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2023-03-12 13:38:39.851 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2023-03-12 13:38:42.559 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 65.
2023-03-12 13:38:45.098 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2023-03-12 13:38:45.727 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 65.
2023-03-12 13:39:27.165 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created test17/[redacted] as a reflection of [redacted]
2023-03-12 13:39:27.222 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created test17/[redacted] as a reflection of [redacted]
2023-03-12 13:59:16.466 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created [redacted] as a reflection of [redacted]
2023-03-12 13:59:16.624 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created [redacted] as a reflection of [redacted]
2023-03-12 14:14:48.096 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:36:08.3825841. Faulted: False.
2023-03-12 14:14:48.104 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2023-03-12 14:15:20.874 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:36:41.0428986. Faulted: False.
2023-03-12 14:15:20.875 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2023-03-12 14:15:23.542 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2023-03-12 14:15:24.184 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 65.
2023-03-12 14:15:25.129 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 65.
2023-03-12 14:21:40.795 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:43:00.9418751. Faulted: False.
2023-03-12 14:21:40.797 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2023-03-12 15:03:11.756 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:48:23.6096623. Faulted: False.
2023-03-12 15:03:11.808 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2023-03-12 15:08:05.109 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:52:44.2333791. Faulted: False.
2023-03-12 15:08:05.110 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2023-03-12 15:08:06.526 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2023-03-12 15:08:07.131 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 65.
2023-03-12 15:08:08.660 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected [redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 65.
2023-03-12 15:14:06.467 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:52:25.6700330. Faulted: False.
2023-03-12 15:14:06.468 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2023-03-12 15:42:21.247 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:39:09.4390564. Faulted: False.
2023-03-12 15:42:21.249 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
```

**Comment by winromulus** [comment] 2023-03-12 16:19
@laemm-line at around what time did you create the new namespace that it missed?

**Comment by winromulus** [comment] 2023-03-12 16:23
@laemm-line  if you still have it running, can you try to do a change on one of the source secrets. I want to make sure that the only missed event is the namespace creation event.

**Comment by laemm-line** [comment] 2023-03-12 16:44
> @laemm-line at around what time did you create the new namespace that it missed?

I created and deleted namespaces multiple times, shortly after the last log messages that I posted.
E.g. a "test19" namespace was created at 2023-03-12T16:11:37Z

> @laemm-line if you still have it running, can you try to do a change on one of the source secrets? I want to make sure that the only missed event is the namespace creation event.

Yes, I still have the same pod running. Changes to the source secret are detected:
```
2023-03-12 16:34:12.222 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created test19/[redacted] as a reflection of [redacted]
2023-03-12 16:34:12.730 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched [redacted] as a reflection of [redacted]
2023-03-12 16:34:12.758 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched [redacted] as a reflection of [redacted]
...
```
After adding some annotation to the secret, it was immediately created in the test19 namespace and was patched in all other namespaces where it existed already.

**Comment by winromulus** [comment] 2023-03-12 16:46
@laemm-line thank you! Seems there's something wrong with the namespace watcher (I think internally some events are not published). I'm trying to reproduce this with the debugger attached.

**Comment by pjaak** [comment] 2023-03-15 01:59
Can confirm similar issue. I have an existing secret, which was updated to add annotations for reflector and reflector didnt pick them up and replicate across namespaces. It wasnt until i delete the reflector pod that it picks it up.

**Comment by winromulus** [comment] 2023-03-16 10:18
@pjaak can you provide some logs and some details about the environment (k8s version, reflector version, if k8s is cloud or self hosted).

**Comment by ppalucha** [comment] 2023-03-16 22:17
I'm just wondering if it may be a memory leak - I'm observing the usage of memory by reflector pod to be constantly growing.

**Comment by KrisJohnstone** [comment] 2023-03-23 00:38
Also have the same problem:
- EKS 1.24.10
- Reflector: 7.0.151

Issue is on namespace create that the secret isn't reflected.

**Comment by pmev0** [comment] 2023-04-20 09:13
i can also confirm this bug. 

- AKS  v1.27.1
- Reflector: 7.0.151

Secret is not replicated immediately to the newly created namespace. Sometimes it takes a good half an hour for it to appear, which makes it unpractical for CI/CD, as the services in the new namespace need the secret on startup.

**Comment by AlexAlterya** [comment] 2023-05-16 09:04
Two hours and counting. I'd like to use it in CI consistently.
```
$ k version --short
[snip]
Server Version: v1.24.10-gke.2300
[/snip]
$ k -n reflector get pod reflector-<blah-blah> -o json | jq -r '.spec.containers[].image' 
emberstack/kubernetes-reflector:7.0.151
```

**Comment by asigachev84** [comment] 2023-06-08 08:49
Same problem
* Kubernetes v1.26.4
* Reflector 7.0.142-amd64

**Comment by BenB196** [comment] 2023-06-16 19:38
Just adding this, it might be an issue more specifically with the secrets watcher/mirror. I ran into this issue with a new namespace, but I'm replicating both a configmap and a secret. The configmap replicated correctly but the secret didn't. So, I don't think it is with the namespace watcher.

**Comment by BenB196** [comment] 2023-06-16 23:40
I was able to recreate this issue with verbose logging enabled, but there still doesn't appear to be enough info.

```
2023-06-16 19:34:55.642 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Namespace test
2023-06-16 19:34:55.649 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap test/kube-root-ca.crt
2023-06-16 19:34:55.649 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Reflecting default/[redacted] to test/[redacted]
2023-06-16 19:34:55.653 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Retrieving default/[redacted]
2023-06-16 19:34:55.668 -04:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created test/[redacted] as a reflection of default/[redacted]
2023-06-16 19:34:55.668 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Secret test/[redacted]
2023-06-16 19:34:55.670 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added Namespace test
2023-06-16 19:34:55.672 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Reflecting default/[redacted] to test/[redacted]
2023-06-16 19:34:55.673 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Retrieving default/[redacted]
2023-06-16 19:34:55.687 -04:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Created test/[redacted] as a reflection of default/[redacted]
2023-06-16 19:34:55.687 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap test/[redacted]
2023-06-16 19:35:05.200 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Deleted Secret test/[redacted]
2023-06-16 19:35:05.260 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Deleted ConfigMap test/kube-root-ca.crt
2023-06-16 19:35:05.264 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Deleted ConfigMap test/[redacted]
2023-06-16 19:35:23.431 -04:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:00.0041755. Faulted: False.
2023-06-16 19:35:23.433 -04:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2023-06-16 19:35:23.438 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Namespace default
2023-06-16 19:35:23.440 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added Namespace default
2023-06-16 19:35:23.441 -04:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:00.0040524. Faulted: False.
2023-06-16 19:35:23.442 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Namespace kube-node-lease
2023-06-16 19:35:23.444 -04:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2023-06-16 19:35:23.446 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added Namespace kube-node-lease
2023-06-16 19:35:23.451 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Namespace kube-public
2023-06-16 19:35:23.452 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Secret default/[redacted]
2023-06-16 19:35:23.458 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added Namespace kube-public
2023-06-16 19:35:23.461 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.SecretMirror) Processing auto-reflection source default/[redacted]
2023-06-16 19:35:23.463 -04:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:01:00.0068750. Faulted: False.
2023-06-16 19:35:23.463 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Namespace kube-system
2023-06-16 19:35:23.467 -04:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2023-06-16 19:35:23.469 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added Namespace kube-system
2023-06-16 19:35:23.475 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap default/kube-root-ca.crt
2023-06-16 19:35:23.472 -04:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected default/[redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2023-06-16 19:35:23.482 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap default/[redacted]
2023-06-16 19:35:23.484 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Secret kube-node-lease/[redacted]
2023-06-16 19:35:23.485 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Processing auto-reflection source default/[redacted]
2023-06-16 19:35:23.486 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Secret kube-public/[redacted]
2023-06-16 19:35:23.493 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Secret kube-system/bootstrap-token-abcdef
2023-06-16 19:35:23.495 -04:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Auto-reflected default/[redacted] where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2023-06-16 19:35:23.495 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Secret kube-system/[redacted]
2023-06-16 19:35:23.496 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-node-lease/kube-root-ca.crt
2023-06-16 19:35:23.499 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-node-lease/[redacted]
2023-06-16 19:35:23.500 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-public/cluster-info
2023-06-16 19:35:23.501 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-public/kube-root-ca.crt
2023-06-16 19:35:23.503 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-public/[redacted]
2023-06-16 19:35:23.504 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/coredns
2023-06-16 19:35:23.507 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/extension-apiserver-authentication
2023-06-16 19:35:23.509 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/kube-proxy
2023-06-16 19:35:23.510 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/kube-root-ca.crt
2023-06-16 19:35:23.511 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/kubeadm-config
2023-06-16 19:35:23.513 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/kubelet-config
2023-06-16 19:35:23.514 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap kube-system/[redacted]
2023-06-16 19:35:35.860 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.SecretMirror) Handling Added Namespace test
2023-06-16 19:35:35.863 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added Namespace test
2023-06-16 19:35:35.865 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Reflecting default/[redacted] to test/[redacted]
2023-06-16 19:35:35.865 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap test/kube-root-ca.crt
2023-06-16 19:35:35.867 -04:00 [DBG] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Retrieving default/[redacted]
2023-06-16 19:35:35.885 -04:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Created test/[redacted] as a reflection of default/[redacted]
2023-06-16 19:35:35.885 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Added ConfigMap test/[redacted]
2023-06-16 19:36:01.419 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Deleted ConfigMap test/kube-root-ca.crt
2023-06-16 19:36:01.423 -04:00 [VRB] (ES.Kubernetes.Reflector.Core.ConfigMapMirror) Handling Deleted ConfigMap test/[redacted]
```

What the logs show:

1. It initially handles the added namespace `test`
2. It detects the deletion of `test`
3. It timesout
4. It refreshes both configmap and secret handling
5. It detects namespace `test` being added again
6. It creates the configmap
7. It does not create the secret, yet the secret mirror detects the namespace being created.

**Comment by BenB196** [comment] 2023-06-17 01:35
Further debugging, I think there is a race condition with `_autoSources` here:

https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs#L130

If you add the following right before the foreach loop:

```c#
Logger.LogTrace("Handling {eventType} {resourceType} {resourceRef} Source Size: {Size}", notification.Type, ns.Kind,
                        ns.GetRef(), _autoSources.Count);
```

When it works correctly, you'd see a log like:

```
Handling Added Namespace test Source Size: 2
```

When it doesn't work correctly you see:

```
Handling Added Namespace test Source Size: 1
```

The value that is always in the _autoSources is `Handling Added Secret kube-system/bootstrap-token-abcdef`, but the actual Secret that you want to reflect is inconsistently present.

A somewhat reliable way I've found to reproduce this issue:

1. Set the timeout to 10 seconds
2. In the default namespace, create a configmap & secret that reflector should autoreflect (allowing all namespaces should work)
3. Start Reflector
4. Create a test namespace
5. Check if both were reflected properly
6. Delete the namespace
7. Wait whatever remains of the 10 second timeout, until the sessions expire
8. Repeat steps 4-7 until you recreate the issue.

The issue is extremely inconsistent, so will most likely take a few times. Also, I've notice that the timeouts can sometimes get out of sync, if this happens I've found it easier to just restart Reflector to keep the logging relatively easy to read.

I've only been able to reproduce the issue with Secrets and not Configmaps, I don't really see much of a difference between them, so not sure why Secrets seems to have the issue.

**Comment by BenB196** [comment] 2023-06-17 13:31
I believe I have been able to track down part of the race condition here.

It appears that there is a race condition between the namespaces thread and the secret & configmap threads, within the `WatcherBackgroundService`/`ResourceMirror` WatcherEvent.

If the namespace thread runs the WatcherEvent case
https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs#L123

Before the configmap and secrets threads run the TResource case

https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs#L69

Then the namespace thread can have a partially populated `_autoReflectionCache`

https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs#L137

For the duration of `timeout`.

This issue manifests for secrets only because, it appears that only the Secrets cache is cleared on `timeout`/`WatcherClosed`

https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs#L69-L73

https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs#L71

https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs#L44-L59

I suspect that only secrets cache being cleared here is actually a different bug, and it should be

```diff
                await Mediator.Publish(new WatcherClosed
                {
-                    ResourceType = typeof(V1Secret),
+                    ResourceType = typeof(TResource),
                    Faulted = sessionFaulted
                }, stoppingToken);
```

To clear all caches, but this also explains why configmap doesn't appear to have the issue, as eventually the namespace cache for configmaps will always have all values, but the secrets will be cleared and restarted new each time.

(Switched `V1Secret` to `TResource` I was also able to produce the bug with Configmaps)


To test the theory of it being a race condition between these two factors, I simply added a delay to the namespace thread prior to the `try` statement in `ExecuteAsync`


https://github.com/emberstack/kubernetes-reflector/blob/12db6cfd5bcf8646fb09b1502475c90905dceff2/src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs#L31-L39


```diff
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var sessionStopwatch = new Stopwatch();
        while (!stoppingToken.IsCancellationRequested)
        {
            var sessionFaulted = false;
            sessionStopwatch.Restart();

+           if (typeof(TResource) == typeof(V1Namespace)) await Task.Delay(1000, stoppingToken);

            try
```

After adding the delay here, I was no longer able to reproduce the bug.

I'm not sure what the best option here is for solving this.

**Comment by BenB196** [comment] 2023-06-17 14:50
Starting off small, I opened this PR https://github.com/emberstack/kubernetes-reflector/pull/358, after making this change alone, I wasn't able to reproduce the issue, I'm not 100% sure this fixes the problem, but it definitely seems to make it less common.

**Comment by BenB196** [comment] 2023-07-17 14:42
I wanted to post a follow up here. Since upgrading to [v7.0.183](https://github.com/emberstack/kubernetes-reflector/releases/tag/v7.0.183) which contains https://github.com/emberstack/kubernetes-reflector/pull/358, I have not been able to replicate this issue anymore. I'm not sure if anyone has tested the newer versions to see if this issue still appears?

**Comment by asigachev84** [comment] 2023-07-17 14:53
@BenB196 I see the same effect. Have a cluster running with v7.0.183 for about 2 weeks. Creating new namespace makes secrets get reflected immediately

**Comment by rayanebel** [comment] 2023-08-21 12:11
We continue to have the same issue on our GKE cluster. We are using the latest version of reflector and after 2 days, the secrets are not sync anymore and we have to restart reflector.

**Comment by BenB196** [comment] 2023-08-21 12:43
Hi @rayanebel,

> We are using the latest version of reflector

Can you provide the exact version you're using? If you are using the `latest` tag, can you confirm that the image has been re-pulled via something like a ImagePullPolicy: Always?

Can you also try enabling debug logging? There was some more logs added in debug to better help troubleshoot this issue.

**Comment by MrKoberman** [comment] 2023-09-01 21:43
After we upgraded to the latest version 7.0.193 even restarting didn't fix the problem.

**Comment by winromulus** [comment] 2023-10-02 22:35
This issue seems to have been fixed with the latest version of the Kubernetes client. Please upgrade and reopen this issue if there's still a problem.

**Closed by winromulus** 2023-10-02 22:35 UTC
Labels: question

**Comment by raxod502-plaid** [comment] 2023-10-03 16:08
"Seems to have been fixed" - can you elaborate on what specific change resolved the problem?

**Comment by winromulus** [comment] 2023-10-03 16:27
@raxod502-plaid upgrading to the latest version of KubernetesClient, I was unable to reproduce the issue anymore on a couple of clusters I have where before the upgrade the issue was persisting. Downgrading restores the issue. I am not sure what they changed in the client that could lead to this since they did some package upgrades as well and isolating the potential fix would consume a lot of my time and is unfeasible (since I would have to rebuild a dependency with other dependencies to isolate it).

The "seems" is based on my testing and I also specified the change that could have led to the potential fix. If the problem can still be reproduced with the latest version, feel free to reopen the issue and provide the requested information (k8s version, hosting type, reflector version and logs).

I'm not sure if your question was implying that I did not do my due diligence in figuring this out, but if it was, then please rest assured that I am doing what I can in spare time to maintain this project and work through the multitude of setup options out there to test this as much as possible.

I stand by what I said, I upgraded KubernetesClient and it seems that fixed the issue (from what I can test). If this issue is still there in some setup I don't have, please reopen the issue and post the environment details and logs and I'll do my best to try to sort it out (contributions are also encouraged if I'm potentially too slow in providing a solution).

**Comment by yukha-dw** [comment] 2024-12-04 05:22
The bug seems still lingering on latest version, but restarting the pod fix the issue for me

- server: 1.30.5-gke
- client: 1.30.5
- emberstack/kubernetes-reflector:7.1.288
