### ISSUE TITLE
AgentStatus=Failed (Initializing), AD=ES.Kubernetes.Reflector[1] Failed to initialize agent: Cannot marshal 'parameter #1': Cannot marshal managed types when the runtime marshalling system is disabled.

### ISSUE THREAD

**Issue by dsaidaa** [emberstack/kubernetes-reflector#339] opened 2023-03-15 23:24 UTC
Hi all
I get an issue while installing the reflector addon.
Here are the logs from the deployment.
The Dynatrace agent is installed in this K8s cluster. How we can fix this issue?

> `AgentStatus=Failed (Initializing), AD=ES.Kubernetes.Reflector[1]
> Failed to initialize agent: Cannot marshal 'parameter #1': Cannot marshal managed types when the runtime marshalling system is disabled.
>    at Dynatrace.OneAgent.Sto.Detail.NativeSemanticTracingApi.NativeMethods.semanticTracing_isChannelEnabled(String name)
>    at Dynatrace.OneAgent.Sto.Detail.NativeSemanticTracingApi.IsChannelEnabled(String name)
>    at Dynatrace.OneAgent.Sto.Trace.IsChannelEnabled(String channelName)
>    at Dynatrace.OneAgent.Sto.Trace.GetChannel(String channelName)
>    at Dynatrace.OneAgent.Sto.SemanticTracer.GetTracer(String channelName, String loggingPrefix, String className, String methodName)
>    at Dynatrace.OneAgent.Sto.SemanticTracer.GetTracer(String channelName, String className, String methodName)
>    at Dynatrace.OneAgent.Agent.InitializeAgent()
> Unhandled exception. System.Reflection.CustomAttributeFormatException: Binary format of the specified custom attribute was invalid.
>    at System.Reflection.CustomAttributeEncodedArgument.ParseAttributeArguments(IntPtr pCa, Int32 cCa, CustomAttributeCtorParameter[]& CustomAttributeCtorParameters, CustomAttributeNamedParameter[]& CustomAttributeTypedArgument, RuntimeAssembly assembly)
>    at System.Reflection.CustomAttributeEncodedArgument.ParseAttributeArguments(ConstArray attributeBlob, CustomAttributeCtorParameter[]& customAttributeCtorParameters, CustomAttributeNamedParameter[]& customAttributeNamedParameters, RuntimeModule customAttributeModule)
>    at System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope, MetadataToken caCtorToken, ConstArray& blob)
>    at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
>    at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target)
>    at System.Reflection.RuntimeMethodInfo.GetCustomAttributesData()
>    at System.Reflection.MemberInfo.get_CustomAttributes()
>    at Serilog.Settings.Configuration.ConfigurationReader.<FindConfigurationExtensionMethods>g__HasExtensionAttribute|32_0(MethodInfo m)
>    at Serilog.Settings.Configuration.ConfigurationReader.<>c.<FindConfigurationExtensionMethods>b__32_3(MethodInfo m)
>    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Serilog.Settings.Configuration.ConfigurationReader.FindConfigurationExtensionMethods(IReadOnlyCollection`1 configurationAssemblies, Type configType)
>    at Serilog.Settings.Configuration.ConfigurationReader.FindSinkConfigurationMethods(IReadOnlyCollection`1 configurationAssemblies)
>    at Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration)
>    at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
>    at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
>    at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
>    at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
>    at Program.<Main>$(String[] args) in /src/ES.Kubernetes.Reflector/Program.cs:line 8
>    at Program.<Main>(String[] args)`

**Comment by winromulus** [comment] 2023-03-15 23:30
@dsaidaa seems that software is interfering with Serilog (semantic logging extension for .Net applications). I have no idea why and how it does this and would not be able to reproduce the issue without that specific software. Either way I can't do any work on this since reflector is a standard .net application and this seems like a very custom scenario with other applications trying to interfere.
I will close this issue since this is not a reflector issue, but an environment issue (other applications using serilog will hit the same problem).

**Closed by winromulus** 2023-03-15 23:30 UTC
