### ISSUE TITLE
Reflector return `invalid status code 'Forbidden'`

### ISSUE THREAD

**Issue by shiyuhang0** [emberstack/kubernetes-reflector#316] opened 2022-11-11 06:39 UTC
I find secret can not be copied into the new namespace sometimes. But I don‘t know what happened at all.

Does the reflector provide some information to help find the reason? for example, logs?

By the way, the following is the error log I find in reflector pod. 
```
[ERR] (ES.Kubernetes.Reflector.Core.SecretMirror) Could not reflect tidb-admin/gateway-letsencrypt-secret to e2etesting-system-test-926-pool/gateway-letsencrypt-secret due to exception.
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.Kubernetes.CreateNamespacedSecretWithHttpMessagesAsync(V1Secret body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedSecretAsync(IKubernetes operations, V1Secret body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.ResourceReflect(KubeRef sourceId, KubeRef targetId, TResource sourceResource, TResource targetResource, Boolean autoReflection) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 432
```

**Comment by winromulus** [comment] 2022-11-16 10:53
Those are the logs. The forbidden means that Reflector does not have access to that namespace (in case you modified the RBAC definitions). I'm going to close this issue since this is a permissions issue in a custom scenario, but if you still get this, please reopen and we can debug.
Summary: check the namespace permissions or resource permissions for the reflector service account.

**Comment by shiyuhang0** [comment] 2022-11-17 08:17
I met this error again.

![7da78b78-53de-47c1-9f64-77b7ed9d1a7b](https://user-images.githubusercontent.com/52435083/202389879-bd22b194-a933-45b2-9dbd-759abbf40eef.jpeg)

I don't think it is a totally permissions issue because it succeeds before this error. I am sorry that I don't know how to reproduce this bug. it happens occasionally.

The following are the things I can provide:

we deployed the reflector with pulumi:
```
const reflector = new k8s.helm.v3.Chart(
    "reflector",
    {
      namespace: "kube-system",
      chart: "reflector",
      version: "6.1.47",
      fetchOpts: {
        repo: "https://emberstack.github.io/helm-charts",
      },
      values: {
        image: {
          repository: "gcr.io/pingcap-public/third-party/emberstack/kubernetes-reflector",
          tag: "6.1.47"
        },
      },
    },
    {
      provider: c.provider,
    }
  );
```

we use reflector like this
```
 "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
 "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "e2etesting-system-.*",
 "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
```

ks8：we use eks which is provided by aws cloud

Please contact me if you need any other infomation.

**Comment by winromulus** [comment] 2022-11-17 08:25
@shiyuhang0 this error occurs if either the namespace is "locked" by something managing permissions or the secret itself.
I'd need to know a lot more about the environment to help you on this.
In summary: Reflector got an update event from k8s and is trying to modify the destination secret but k8s rejects it due to permissions either on the namespace or the secret. It's not something reflector controls at all (at installation the RBAC definition requests permissions for all namespaces and all secrets so it can reflect changes, but if something changes that, k8s rejects the change)

**Comment by Roming22** [comment] 2023-01-27 22:22
I've also run into the issue. In my case, because I'm deploying the reflector using openshift-gitops, I needed to use kustomize to set the `subjects[0].namespace` to the namespace in which the reflector user was created.

**Comment by winromulus** [comment] 2023-03-05 01:01
Please try the new version. This issue should be fixed. Please reopen if this is still a problem (some scenarios are extremely hard to reproduce and help is required to validate the fix).

**Closed by winromulus** 2023-03-05 01:01 UTC
Labels: question, not a problem
