### ISSUE TITLE
Is there an option to copy label in secrets or configmaps?

### ISSUE THREAD

**Issue by dmfrey** [emberstack/kubernetes-reflector#420] opened 2024-03-11 15:27 UTC
I'm using `reflector` to mirror Minio credentials for Cloud Native PostgresSQL, CNPG, to be able to implement WAL archiving.  CNPG will look for a label called `cnpg.io/reload` to reload the db instances when the secret changes. 

When I look at the secret that gets mirrored into the namespace, the labels are blank. The Secret being mirrored, however, does have the label. It's not reflected on the mirrored copy.

**Comment by tamasborsstriva** [comment] 2024-03-12 14:59
I have similar issue, but with **annotations**

with cert-manager, I am adding the following annotations to the generated secret:
```
annotations:
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  com.flanksource/vcluster-sync: "true"
``` 

but the mirrored secret in the "other" namesapce does not have `com.flanksource/vcluster-sync` annotation


however, when  I add any annotation later to the mirrored secret, it will stay, even after changing the data of the source/original secret

**Comment by winromulus** [comment] 2024-03-12 15:03
This issue is a duplicate of #414 (for labels) and #418 (for annotations). Please describe your requested feature and behavior there so we can establish how it's supposed to work.
I will close this issue and continue the discussion there...

**Closed by winromulus** 2024-03-12 15:03 UTC
